# Week 6 activities: Data wrangling using pandas

# Setup

In [17]:
# packages
import pandas as pd
import numpy as np
import os

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Load the data: you'll need to edit your path
# I recommend moving this notebook into your "myactivities" repo, 
# creating a folder in that repo for data, moving the data there, and loading from there

In [18]:
os.getcwd()

'/Users/zarayaguilar/ppol5203_f26_myactivities/week6_activity'

In [19]:
df = pd.read_csv("//Users/zarayaguilar/ppol5203_f26_myactivities/week6_activity/childnoinsur_complete.csv")
df.head()

,State,Race,Year,uninsured_rate,Census_Division
0,Wyoming,Non-Hispanic White,2018,0.07,Mountain
1,Wyoming,Hispanic or Latino,2018,0.06,Mountain
2,Wyoming,Black or African American,2018,0.02,Mountain
3,Wyoming,Asian and Pacific Islander,2018,0.02,Mountain
4,Wisconsin,Two or more races,2018,0.02,East North Central

# Activity 1: attributes of dataframes

Using the data loaded above, answer the following questions:

A. What are the unique racial/ethnic categories in the data?

B. What is the maximum and minimum child uninsurance rate?

C. What is the earliest and latest year in the data?

D. Which state(s) has the most observations? Which state(s) has the fewest? (note: this version of the dataset omits state-row-categories with missing data on the uninsurance rate; next week, we'll work with a version that retains observations with those missing values)

*Hint*: for part D you may want to use sort_values() - documentation is here: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html

In [23]:
## A. Unique racial/ethnic categories in the data 
df.Race.value_counts()
set(df.Race)

## Another method to get unique values in the Race column
df.describe()

## B. Max and Min child uninsurance rate 
print("Min year " + str(df.Year.unique().min()))
print("Max year " + str(df.Year.unique().max()))
print("Min child uninsured rate is " + str(df.uninsured_rate.min()))
print("Max child uninsured rate is " + str(df.uninsured_rate.max()))


##Another way to find the same values 
df.Year.unique().min()
df.Year.unique().max()
df.uninsured_rate.min()
df.uninsured_rate.max()


## C. Earliest and Latest year in the data 
df.describe()
## D. Which states have the most observations? Which states have the fewest obervations? 
df.State.value_counts().sort_values()

##Decending order 
df.State.value_counts().sort_values(ascending=False)

Race
Non-Hispanic White                  350
Two or more races                   329
Hispanic or Latino                  320
Black or African American           288
Asian and Pacific Islander          274
American Indian or Alaska Native    153
Name: count, dtype: int64

{'American Indian or Alaska Native',
 'Asian and Pacific Islander',
 'Black or African American',
 'Hispanic or Latino',
 'Non-Hispanic White',
 'Two or more races'}

              Year  uninsured_rate
count  1714.000000     1714.000000
mean   2020.544341        0.054195
std       2.444376        0.035869
min    2017.000000        0.010000
25%    2018.000000        0.030000
50%    2021.000000        0.040000
75%    2023.000000        0.070000
max    2024.000000        0.240000

Min year 2017
Max year 2024
Min child uninsured rate is 0.01
Max child uninsured rate is 0.24

np.int64(2017)

np.int64(2024)

0.01

0.24

              Year  uninsured_rate
count  1714.000000     1714.000000
mean   2020.544341        0.054195
std       2.444376        0.035869
min    2017.000000        0.010000
25%    2018.000000        0.030000
50%    2021.000000        0.040000
75%    2023.000000        0.070000
max    2024.000000        0.240000

State
Vermont           14
Wyoming           16
North Dakota      22
West Virginia     24
South Dakota      24
New Hampshire     25
Mississippi       26
Maine             27
Montana           28
Utah              28
Rhode Island      29
Hawaii            30
Alaska            30
Idaho             31
Delaware          31
Arkansas          33
Nebraska          33
Louisiana         34
Kansas            35
Massachusetts     35
South Carolina    36
New Mexico        36
Nevada            36
Missouri          36
Maryland          36
Florida           36
Georgia           36
Oregon            37
Tennessee         37
Iowa              37
Virginia          38
Connecticut       38
Wisconsin         38
Kentucky          38
New Jersey        38
Indiana           38
Alabama           39
Ohio              39
Pennsylvania      39
Illinois          39
Texas             40
Colorado          40
Michigan          40
New York          41
Minnesota         41
Oklahoma          42
North Carolina    42
California        42
Washington        42
Arizona           42
Name: count, dtype: int64

State
Arizona           42
North Carolina    42
Oklahoma          42
Washington        42
California        42
New York          41
Minnesota         41
Michigan          40
Colorado          40
Texas             40
Illinois          39
Pennsylvania      39
Ohio              39
Alabama           39
Indiana           38
Kentucky          38
Wisconsin         38
Connecticut       38
Virginia          38
New Jersey        38
Iowa              37
Tennessee         37
Oregon            37
Nevada            36
South Carolina    36
New Mexico        36
Maryland          36
Missouri          36
Florida           36
Georgia           36
Massachusetts     35
Kansas            35
Louisiana         34
Nebraska          33
Arkansas          33
Idaho             31
Delaware          31
Hawaii            30
Alaska            30
Rhode Island      29
Utah              28
Montana           28
Maine             27
Mississippi       26
New Hampshire     25
South Dakota      24
West Virginia     24
North Dakota      22
Wyoming           16
Vermont           14
Name: count, dtype: int64

# Activity 2: selecting and filtering

A. Subset the data to the State == `California`. Store the resulting dataframe as `ca_df` and use the `shape` command to print the dimensions

In [30]:
## State = California -- store in new dataframe (ca_df) ad shape command to print dimensions 

ca_df = df[df.State == "California"].copy()
ca_df.head()
ca_df.shape

,State,Race,Year,uninsured_rate,Census_Division
227,California,Two or more races,2018,0.02,Pacific
228,California,Non-Hispanic White,2018,0.02,Pacific
229,California,Hispanic or Latino,2018,0.04,Pacific
230,California,Black or African American,2018,0.02,Pacific
231,California,Asian and Pacific Islander,2018,0.02,Pacific

(42, 5)

B. Use list comprehension and the `columns` attribute to create a list of columns, called `cols_keep` that excludes the following two columns: 
- `State`
- `Census_Division`

Print the list. It should contain columns for Race, Year, and uninsured_rate

In [31]:
## 

cols_keep = [col for col in ca_df.columns if col not in ["State", "Census_Division", ]]
cols_keep

['Race', 'Year', 'uninsured_rate']

C. Use the `cols_keep` list to create a new dataset, `ca_df_clean` that removes those two columns. Print the head

In [32]:
## your code here
ca_df_clean = df_ca[cols_keep].copy()
ca_df_clean.head()

                           Race  Year  uninsured_rate
227           Two or more races  2018            0.02
228          Non-Hispanic White  2018            0.02
229          Hispanic or Latino  2018            0.04
230   Black or African American  2018            0.02
231  Asian and Pacific Islander  2018            0.02

D. Write a user-defined function, `subset_onerace` that takes in three arguments:
- A string for a racial/ethnic group
- A string representing the name of the race/ethnicity column
- A dataframe

And subset the data to rows of data for that race/ethnicity

In [34]:
## your code here
def subset_onerace(one_race, race_colname, df):
    """
    one_race: string for race/ethnicity category
    race_colname: str with name of the race/ethnicity column
    df: dataset
    Returns: dataset subsetted to that race/ethnicity 
    """
    # one approach
    df_sub = df[df[race_colname] == one_race]
    # could also use query and the like approach if want to match more incomplete category names
    return df_sub

E. Use that user-defined function to return the rows for `American Indian or Alaska Native`, ordered by year from lowest to highest. Has the uninsurance rate among children gone up or down over time?

In [35]:
## your code here

ca_df_clean.Race.value_counts()
subset_onerace(one_race = "American Indian or Alaska Native",
              race_colname = "Race",
              df = ca_df_clean).sort_values(by = 'Year')

Race
Two or more races                   7
Non-Hispanic White                  7
Hispanic or Latino                  7
Black or African American           7
Asian and Pacific Islander          7
American Indian or Alaska Native    7
Name: count, dtype: int64

                                  Race  Year  uninsured_rate
278   American Indian or Alaska Native  2017            0.08
232   American Indian or Alaska Native  2018            0.08
1203  American Indian or Alaska Native  2019            0.07
1250  American Indian or Alaska Native  2021            0.05
723   American Indian or Alaska Native  2022            0.05
1681  American Indian or Alaska Native  2023            0.06
770   American Indian or Alaska Native  2024            0.04

F. Using list comprehension, iterate over the unique race/ethnicity groups in `ca_df_clean` and apply that function to create a subset of rows ordered by year for that group; the result will be a list of dataframes

Print the result; what patterns do you notice?

In [39]:
## your code here
separate_groups = [subset_onerace(one_race = "American Indian or Alaska Native",
                                  race_colname = "Race",
                                  df = ca_df_clean).sort_values(by = 'Year')
                  for group in ca_df_clean.Race.unique()]


separate_groups

[                                  Race  Year  uninsured_rate
 278   American Indian or Alaska Native  2017            0.08
 232   American Indian or Alaska Native  2018            0.08
 1203  American Indian or Alaska Native  2019            0.07
 1250  American Indian or Alaska Native  2021            0.05
 723   American Indian or Alaska Native  2022            0.05
 1681  American Indian or Alaska Native  2023            0.06
 770   American Indian or Alaska Native  2024            0.04,
                                   Race  Year  uninsured_rate
 278   American Indian or Alaska Native  2017            0.08
 232   American Indian or Alaska Native  2018            0.08
 1203  American Indian or Alaska Native  2019            0.07
 1250  American Indian or Alaska Native  2021            0.05
 723   American Indian or Alaska Native  2022            0.05
 1681  American Indian or Alaska Native  2023            0.06
 770   American Indian or Alaska Native  2024            0.04,
                                   Race  Year  uninsured_rate
 278   American Indian or Alaska Native  2017            0.08
 232   American Indian or Alaska Native  2018            0.08
 1203  American Indian or Alaska Native  2019            0.07
 1250  American Indian or Alaska Native  2021            0.05
 723   American Indian or Alaska Native  2022            0.05
 1681  American Indian or Alaska Native  2023            0.06
 770   American Indian or Alaska Native  2024            0.04,
                                   Race  Year  uninsured_rate
 278   American Indian or Alaska Native  2017            0.08
 232   American Indian or Alaska Native  2018            0.08
 1203  American Indian or Alaska Native  2019            0.07
 1250  American Indian or Alaska Native  2021            0.05
 723   American Indian or Alaska Native  2022            0.05
 1681  American Indian or Alaska Native  2023            0.06
 770   American Indian or Alaska Native  2024            0.04,
                                   Race  Year  uninsured_rate
 278   American Indian or Alaska Native  2017            0.08
 232   American Indian or Alaska Native  2018            0.08
 1203  American Indian or Alaska Native  2019            0.07
 1250  American Indian or Alaska Native  2021            0.05
 723   American Indian or Alaska Native  2022            0.05
 1681  American Indian or Alaska Native  2023            0.06
 770   American Indian or Alaska Native  2024            0.04,
                                   Race  Year  uninsured_rate
 278   American Indian or Alaska Native  2017            0.08
 232   American Indian or Alaska Native  2018            0.08
 1203  American Indian or Alaska Native  2019            0.07
 1250  American Indian or Alaska Native  2021            0.05
 723   American Indian or Alaska Native  2022            0.05
 1681  American Indian or Alaska Native  2023            0.06
 770   American Indian or Alaska Native  2024            0.04]

# Activity 3: creating and recoding variables

A. Going back to the full dataset, `df`, create a new variable in the dataset, `race_simplified`, that:

- Converts the string to lowercase
- Replaces spaces with _ 

Use `pd.crosstab` with the two variables to make sure the recoding worked

In [40]:
## your code here

df['race_simplified'] = df.Race.str.replace(" ", "_").str.lower()
pd.crosstab(df.Race, df.race_simplified)

race_simplified,american_indian_or_alaska_native,asian_and_pacific_islander,black_or_african_american,hispanic_or_latino,non-hispanic_white,two_or_more_races
Race,,,,,,
American Indian or Alaska Native,153,0,0,0,0,0
Asian and Pacific Islander,0,274,0,0,0,0
Black or African American,0,0,288,0,0,0
Hispanic or Latino,0,0,0,320,0,0
Non-Hispanic White,0,0,0,0,350,0
Two or more races,0,0,0,0,0,329

B. In the full dataset, use `np.mean` to find the nationwide average uninsurance rate. Create a variable, `ur_demean` that subtracts that national average from each individual `uninsured_rate`

Use .describe() to confirm the de-meaning worked (the overall variable mean should be very close to zero and min and max should change)

In [53]:
## your code here

df['ur_demean'] = df.uninsured_rate = np.mean(df.uninsured_rate)

df.describe()



pd.option_context('display.float_format', '{:,.2f}'.format)
ur_mean = np.mean(df.uninsured_rate)
df['ur_demean'] = df.uninsured_rate - ur_mean 

df.describe()

              Year  uninsured_rate     ur_demean
count  1714.000000    1.714000e+03  1.714000e+03
mean   2020.544341    5.419487e-02  5.419487e-02
std       2.444376    9.023195e-16  9.023195e-16
min    2017.000000    5.419487e-02  5.419487e-02
25%    2018.000000    5.419487e-02  5.419487e-02
50%    2021.000000    5.419487e-02  5.419487e-02
75%    2023.000000    5.419487e-02  5.419487e-02
max    2024.000000    5.419487e-02  5.419487e-02

              Year  uninsured_rate     ur_demean
count  1714.000000    1.714000e+03  1.714000e+03
mean   2020.544341    5.419487e-02 -2.081668e-17
std       2.444376    9.023195e-16  0.000000e+00
min    2017.000000    5.419487e-02 -2.081668e-17
25%    2018.000000    5.419487e-02 -2.081668e-17
50%    2021.000000    5.419487e-02 -2.081668e-17
75%    2023.000000    5.419487e-02 -2.081668e-17
max    2024.000000    5.419487e-02 -2.081668e-17

C. In the full dataset, use `np.select` to create a new variable, `type_statename` that codes state names into two categories:
    
    - two_words: if the name has multiple words (eg North Carolina, New Jersey, etc)
    - one_word: if the name has a single word
        
Hint: you can do this by checking whether the name string contains any spaces, comparing the length of the string to the number of alpha characters, or another approach

Spot check your work using the `sample` command

In [54]:
## your code here







conditions = [df.State.str.contains(" "),
              ~df.State.str.contains(" ")]
choices = ["two_words", "one_word"]

df['type_statename'] = np.select(
    conditions,
    choices,
    default='single-word'
)
df.sample()

,State,Race,Year,uninsured_rate,Census_Division,race_simplified,ur_demean,type_statename
358,Massachusetts,Black or African American,2017,0.054195,New England,black_or_african_american,-2.081668e-17,one_word

# Activity 4: grouping and aggregation

A. Group the dataset by `Census_Division`. Use a for loop to print the group names

In [58]:
## your code here
cd_groups = df.groupby("Census_Division")
for group, data in cd_groups: 
    print(group)
    print(data.head())

East North Central
       State                        Race  Year  uninsured_rate  \
4  Wisconsin           Two or more races  2018        0.054195
5  Wisconsin          Non-Hispanic White  2018        0.054195
6  Wisconsin          Hispanic or Latino  2018        0.054195
7  Wisconsin   Black or African American  2018        0.054195
8  Wisconsin  Asian and Pacific Islander  2018        0.054195

      Census_Division             race_simplified     ur_demean type_statename
4  East North Central           two_or_more_races -2.081668e-17       one_word
5  East North Central          non-hispanic_white -2.081668e-17       one_word
6  East North Central          hispanic_or_latino -2.081668e-17       one_word
7  East North Central   black_or_african_american -2.081668e-17       one_word
8  East North Central  asian_and_pacific_islander -2.081668e-17       one_word
East South Central
        State                        Race  Year  uninsured_rate  \
36  Tennessee           Two or more races  2018        0.054195
37  Tennessee          Non-Hispanic White  2018        0.054195
38  Tennessee          Hispanic or Latino  2018        0.054195
39  Tennessee   Black or African American  2018        0.054195
40  Tennessee  Asian and Pacific Islander  2018        0.054195

       Census_Division             race_simplified     ur_demean  \
36  East South Central           two_or_more_races -2.081668e-17
37  East South Central          non-hispanic_white -2.081668e-17
38  East South Central          hispanic_or_latino -2.081668e-17
39  East South Central   black_or_african_american -2.081668e-17
40  East South Central  asian_and_pacific_islander -2.081668e-17

   type_statename
36       one_word
37       one_word
38       one_word
39       one_word
40       one_word
Middle Atlantic
           State                        Race  Year  uninsured_rate  \
53  Pennsylvania           Two or more races  2018        0.054195
54  Pennsylvania          Non-Hispanic White  2018        0.054195
55  Pennsylvania          Hispanic or Latino  2018        0.054195
56  Pennsylvania   Black or African American  2018        0.054195
57  Pennsylvania  Asian and Pacific Islander  2018        0.054195

    Census_Division             race_simplified     ur_demean type_statename
53  Middle Atlantic           two_or_more_races -2.081668e-17       one_word
54  Middle Atlantic          non-hispanic_white -2.081668e-17       one_word
55  Middle Atlantic          hispanic_or_latino -2.081668e-17       one_word
56  Middle Atlantic   black_or_african_american -2.081668e-17       one_word
57  Middle Atlantic  asian_and_pacific_islander -2.081668e-17       one_word
Mountain
      State                        Race  Year  uninsured_rate Census_Division  \
0   Wyoming          Non-Hispanic White  2018        0.054195        Mountain
1   Wyoming          Hispanic or Latino  2018        0.054195        Mountain
2   Wyoming   Black or African American  2018        0.054195        Mountain
3   Wyoming  Asian and Pacific Islander  2018        0.054195        Mountain
27     Utah           Two or more races  2018        0.054195        Mountain

               race_simplified     ur_demean type_statename
0           non-hispanic_white -2.081668e-17       one_word
1           hispanic_or_latino -2.081668e-17       one_word
2    black_or_african_american -2.081668e-17       one_word
3   asian_and_pacific_islander -2.081668e-17       one_word
27           two_or_more_races -2.081668e-17       one_word
New England
             State                       Race  Year  uninsured_rate  \
26         Vermont         Non-Hispanic White  2018        0.054195
50    Rhode Island         Non-Hispanic White  2018        0.054195
51    Rhode Island         Hispanic or Latino  2018        0.054195
52    Rhode Island  Black or African American  2018        0.054195
104  New Hampshire          Two or more races  2018        0.054195

    Census_Division            race_simplified     ur_demean type_statename
26      New England         non-hispanic_white -2.081668e-17       one_word
50      New England         non-hispanic_white -2.081668e-17      two_words
51      New England         hispanic_or_latino -2.081668e-17      two_words
52      New England  black_or_african_american -2.081668e-17      two_words
104     New England          two_or_more_races -2.081668e-17      two_words
Pacific
         State                        Race  Year  uninsured_rate  \
15  Washington           Two or more races  2018        0.054195
16  Washington          Non-Hispanic White  2018        0.054195
17  Washington          Hispanic or Latino  2018        0.054195
18  Washington   Black or African American  2018        0.054195
19  Washington  Asian and Pacific Islander  2018        0.054195

   Census_Division             race_simplified     ur_demean type_statename
15         Pacific           two_or_more_races -2.081668e-17       one_word
16         Pacific          non-hispanic_white -2.081668e-17       one_word
17         Pacific          hispanic_or_latino -2.081668e-17       one_word
18         Pacific   black_or_african_american -2.081668e-17       one_word
19         Pacific  asian_and_pacific_islander -2.081668e-17       one_word
South Atlantic
            State                        Race  Year  uninsured_rate  \
10  West Virginia           Two or more races  2018        0.054195
11  West Virginia          Non-Hispanic White  2018        0.054195
12  West Virginia          Hispanic or Latino  2018        0.054195
13  West Virginia   Black or African American  2018        0.054195
14  West Virginia  Asian and Pacific Islander  2018        0.054195

   Census_Division             race_simplified     ur_demean type_statename
10  South Atlantic           two_or_more_races -2.081668e-17      two_words
11  South Atlantic          non-hispanic_white -2.081668e-17      two_words
12  South Atlantic          hispanic_or_latino -2.081668e-17      two_words
13  South Atlantic   black_or_african_american -2.081668e-17      two_words
14  South Atlantic  asian_and_pacific_islander -2.081668e-17      two_words
West North Central
           State                              Race  Year  uninsured_rate  \
41  South Dakota                 Two or more races  2018        0.054195
42  South Dakota                Non-Hispanic White  2018        0.054195
43  South Dakota         Black or African American  2018        0.054195
44  South Dakota  American Indian or Alaska Native  2018        0.054195
76  North Dakota                 Two or more races  2018        0.054195

       Census_Division                   race_simplified     ur_demean  \
41  West North Central                 two_or_more_races -2.081668e-17
42  West North Central                non-hispanic_white -2.081668e-17
43  West North Central         black_or_african_american -2.081668e-17
44  West North Central  american_indian_or_alaska_native -2.081668e-17
76  West North Central                 two_or_more_races -2.081668e-17

   type_statename
41      two_words
42      two_words
43      two_words
44      two_words
76      two_words
West South Central
    State                        Race  Year  uninsured_rate  \
31  Texas           Two or more races  2018        0.054195
32  Texas          Non-Hispanic White  2018        0.054195
33  Texas          Hispanic or Latino  2018        0.054195
34  Texas   Black or African American  2018        0.054195
35  Texas  Asian and Pacific Islander  2018        0.054195

       Census_Division             race_simplified     ur_demean  \
31  West South Central           two_or_more_races -2.081668e-17
32  West South Central          non-hispanic_white -2.081668e-17
33  West South Central          hispanic_or_latino -2.081668e-17
34  West South Central   black_or_african_american -2.081668e-17
35  West South Central  asian_and_pacific_islander -2.081668e-17

   type_statename
31       one_word
32       one_word
33       one_word
34       one_word
35       one_word

B. Use `get_group` to extract the Pacific region group and find the mean `uninsured_rate` for states/years/racial/ethnic groups in that group

In [59]:
## your code here

cd_groups.get_group("Mountain").uninsured_rate.mean()

np.float64(0.054194865810968516)

C. Going back to the full dataset, group by `Census_Division` and find the mean uninsurance rate within that group across all states/years. Was the Mountain region higher or lower than other regions in terms of its child uninsurance rate? Which region has the lowest uninsurance rate?

In [60]:
## your code here
df.groupby("Census_Division")['uninsured_rate'].mean().reset_index().sort_values(by = 
                                                                                'uninsured_rate')

      Census_Division  uninsured_rate
4         New England        0.054195
0  East North Central        0.054195
1  East South Central        0.054195
2     Middle Atlantic        0.054195
3            Mountain        0.054195
5             Pacific        0.054195
6      South Atlantic        0.054195
7  West North Central        0.054195
8  West South Central        0.054195

D. Use `groupby` and the built-in `idxmax` aggregation function to:
    
- Group by race/ethnic group (`Race`)
- Find the year and state with the highest uninsurance rate for that race/ethnic group

Hint: there are multiple approaches for how to pull the columns tied to the row with the maximum uninsurance rate, including .loc and sort_values()

In [61]:
## your code here
df.loc[df.groupby('Race')['uninsured_rate'].idxmax(),
       ['Race', 'State', 'Year', 'uninsured_rate']]

                               Race      State  Year  uninsured_rate
9  American Indian or Alaska Native  Wisconsin  2018        0.054195
3        Asian and Pacific Islander    Wyoming  2018        0.054195
2         Black or African American    Wyoming  2018        0.054195
1                Hispanic or Latino    Wyoming  2018        0.054195
0                Non-Hispanic White    Wyoming  2018        0.054195
4                 Two or more races  Wisconsin  2018        0.054195

E. Use `groupby`, `agg`, and a lambda function to:

- Group by race/ethnic group (`Race`)
- Find the interquartile range of uninsurance rates for each race/ethnicity group across states and years. Which groups vary the most?

In [62]:
## your code here 

df.groupby('Race').agg(ur_iqr = 
                       ('uninsured_rate', 
                        lambda x: np.percentile(x, 0.75 ) - np.percentile(x, 0.25)))

                                  ur_iqr
Race
American Indian or Alaska Native     0.0
Asian and Pacific Islander           0.0
Black or African American            0.0
Hispanic or Latino                   0.0
Non-Hispanic White                   0.0
Two or more races                    0.0